Countdown:
  messageInterval: 1000
  legacyFile: web_root/ksc.json
  portSwitchInterval: 5000
  KSC:
    host: countdown.ksc.nasa.gov
    Ports:
      primary: 11142
      secondary: 11143
  VAFB:
    host: countdown.ksc.nasa.gov
    Ports:
      primary: 11144
      secondary: 11145
Server:
  port: 8080
  webSocketPath: /ws
  differentialUpdate: true
